### ISSUE TITLE
Import/export collection items

### ISSUE THREAD

**Issue by ulysse-lacour** [tractr/directus-sync#89] opened 2024-07-17 15:58 UTC
This is not a complain more a feature suggestion/question.

I'm unable to import/export collections items, only data models. Is this feature already implementend and I missed it ?
If not being able to sync both collections and their items would be absolutely amazing.

In my case I'm using dockerize directus and postgis and only looking for a way to transfer collections items for dev to prod back and forth.

**Comment by vwasteels** [comment] 2024-07-31 13:56
potential duplicate of https://github.com/tractr/directus-sync/issues/1

**Comment by EdouardDem** [comment] 2024-09-16 02:59
Yes it is a duplicate of #1

**Closed by EdouardDem** 2024-09-16 02:59 UTC
